### ISSUE TITLE
Line and paragraph spacing

### ISSUE THREAD

**Issue by bugadani** [embedded-graphics/embedded-text#100]
cc @rfuest (because of [this comment](https://github.com/embedded-graphics/embedded-text/pull/90#discussion_r555251244))

The current idea would be to provide 2(+1) functions:
 - `line_height`
 - `line_spacing`
 - (later a `paragraph_spacing` similar to `line_spacing` but it's far off)

Both of these functions would set the distance between baselines, but `line_height` would use pixels, while `line_spacing` would use a multiplicative  factor (probably `f32` simply because I find fixed point unwieldy) value. The latter would somewhat align to what word processors are doing, while the former doesn't require f32 support.

Internally, `line_spacing` could be something like a multiply-and-round implementation calling `line_height`.

Do you have any better idea for line spacing? One drawback is that it would lock `paragraph_spacing` into using an `f32` value without a `line_height` analogue that would set spacing in pixels (thinking about it some more, a pixel-based paragraph spacing would also be confusing if it had the same meaning as line_height - I can imagine what a surprise it would be if a `paragraph_spacing` of 12 pixels would result in 4px of space...).

**Comment by rfuest** [comment]
I suppose you mean functions inside the style constructor?

Mixing `line_height` and `line_spacing` might get confusing. I would stick with `line_height`, which is also used in CSS. If `line_spacing(self, factor: f32)` is only a constructor function, we could replace it by a `line_height_percent(self, percent: u32)`. This could easily be implemented without floating point and setting the line height in percent is very common. A `line_height_relative(self, delta: i32)`, which just adds delta to the default line height, could also be useful.

Paragraph spacing in DTP applications is always additive. If you set the paragraph spacing to 0 the lines just continue as normal, without any additional space. Any value > 0 adds additional space between the first line of the new paragraph and the last line of the previous paragraph. So IMO `paragraph_spacing` should be an `i32`, that is added to the y coordinate of the position, before the first line of the next paragraph is drawn.

> cc @rfuest (because of [this comment](https://github.com/embedded-graphics/embedded-text/pull/90#discussion_r555251244))

Feel free to bug me anytime you could use a second pair of eyes to look at e-t code or discuss new features.

**Comment by bugadani** [comment]
> Feel free to bug me anytime you could use a second pair of eyes to look at e-t code or discuss new features.

Thanks, I shall do that! :)

What do you think about providing a single `line_height` function, that takes a `LineHeight` value, constructed via extensions on u8/u32? Usage would look something like `style.line_height(300.percent())` or `style.line_height(16.px())` or similar (even `16 * px` but after playing around some with that style of code I think I'd not do that).
This way, a single API could cover both relative and absolute line heights, and usage wouldn't be horrible either.

I think I prefer `u32` over `i32` here. The conversion is trivial, but taking `i32` would have some horrible side effects like drawing bottom-to-up where most of the code really doesn't expect that, I think. Using `u32`, worst case everything gets drawn in a single line.

**Comment by rfuest** [comment]
> What do you think about providing a single `line_height` function, that takes a `LineHeight` value, constructed via extensions on u8/u32? Usage would look something like `style.line_height(300.percent())` or `style.line_height(16.px())` or similar (even `16 * px` but after playing around some with that style of code I think I'd not do that).
> This way, a single API could cover both relative and absolute line heights, and usage wouldn't be horrible either.

So, like similar to this suggestions, which you found too complicated a month ago? :wink: 
https://github.com/embedded-graphics/embedded-graphics/pull/534#issuecomment-769205646

I think that the enum instead of different functions in the constructor is a good idea. This should also make it easier to keep the line height and font settings independent from each other, if you e.g. change the font after setting a line height of 150%.

Should we only support absolute pixel heights and percentages or also relative pixel delta, that is added to the default height? I'm not sure how the extensions methods would be called in that case. `16.px()` could be interpreted as an absolute line height of 16px or and an increase of the default line height by 16px.

> I think I prefer `u32` over `i32` here. The conversion is trivial, but taking `i32` would have some horrible side effects like drawing bottom-to-up where most of the code really doesn't expect that, I think. Using `u32`, worst case everything gets drawn in a single line.

I agree that `line_height` and later `paragraph_spacing` should be `u32` to keep things easy. If we add an relative option for the line height, that adds an delta to the default line height, it should be an `i32` to be more flexible.  But to keep rendering easy the addition between the default line height and the delta should be clamped to a minimum value of 0.

**Comment by bugadani** [comment]
> So, like similar to this suggestions, which you found too complicated a month ago? 😉

Yes, I can see reason eventually :) But only with the extension methods! Without those, the enum still smells clunky.

In this case I'd probably go without relative options and just have absolute and percentage. Working with pixels is the same "now it looks good enough with a value of X" so relative setting sounds a bit redundant. `line_height(16.px())` should unambiguously mean "the line will be 16 px high", IMO.

**Comment by rfuest** [comment]
> `line_height(16.px())` should unambiguously mean "the line will be 16 px high", IMO.

Yes, it does if no relative option exists. It looks good and the only problem I have with this approach is that no other pixel dimension in e-g needs a `.px()` suffix. Perhaps `line_height_px(height: u32)`, `line_height_percent(percent: u32)` would be more consistent with the rest of the API, if you don't like `line_height(LineHeight::Absolute(123))` and `line_height(LineHeight::Percent(123))`

**Comment by bugadani** [comment]
There could be an implicit u32 -> LineHeight::Px (`fn line_height(height: impl Into<LineHeight>) {...}`) conversion in there. A little bit of complexity, though.

**Comment by rfuest** [comment]
IMO the unit of a value should be explicitly specified by the caller if a value can have different units. The automatic conversion from `u32` to a pixel height doesn't make the unit obvious.

**Comment by bugadani** [comment]
That makes sense. My problem with the multiple functions approach is that adding a new unit adds a new function to the builder and that inflates the API surface, as well as adds noise to the documentation.

If we were to add an `em` unit, having 3 methods to set line height and 3 more for paragraph spacing, I think that would be more methods than what the builder currently has.

I think in this case, while a bit weird compared to the rest of the API, the extension method style will in long term result in less duplication, at least.

**Comment by rfuest** [comment]
OK, good point. Let's go with one method per setting that takes an enum argument.

I wouldn't mind to use `.line_height(LineHeight::Percent(150))` directly, without an extension trait. Other style properties also use enums, so this doesn't look out of place IMO. But I guess the extension trait won't hurt.

I also want to add `line_height` support to e-g's `TextStyle`. Should we add separate `LineHeight` enums for e-g and e-t or do we want to share one? I think we would have the same supported units at the moment but the feature set might diverge in the future.

**Comment by bugadani** [comment]
For now, we can use the same type. If at any point e-t needs something extra, I (think) can always add a conversion.

**Comment by rfuest** [comment]
OK, I'll try to add the feature soon. How should the enum look like? Like this?
```rust
pub enum LineHeight {
    /// Line height in pixels.
    Px(u32),

    /// Line height in percent of the default line height.
    Percent(u32),
}

impl Default for LineHeight {
    // return LineHeight::Percent(100)
}
```

**Comment by bugadani** [comment]
Hmm I haven't considered `Default`, that 100% looks reasonable.

I think I prefer `Pixels` - there is little need to abbreviate the name. The comments sound a bit redundant, to be fair, but I can't do better here either.

You don't have to hurry, there's still work to be done before I could get to this.

**Comment by rfuest** [comment]
> I think I prefer `Pixels` - there is little need to abbreviate the name. The comments sound a bit redundant, to be fair, but I can't do better here either.

I wasn't sure about this one. While I also prefer `Pixels` as the enum variant, but I would prefer `123.px()` over `123.pixels()` for the extension trait. And IMO both should be the same.

**Comment by rfuest** [comment]
But perhaps they don't have to be the same. I think the STM32 HALs also use `.hz()`, but the type is called `Hertz`.

**Comment by bugadani** [comment]
Naming is hard. I'd go with `.px()` and `Pixels`, as well as `Percentage` and ?? (`.pc()` or `.pct()` would be analogous, but confusing, `.percent()` is fine, but if one is abbreviated and the other is not, well...)

**Comment by rfuest** [comment]
I think `px` and `percent` are OK.

Here is a revised version of the API (comments are WIP):

```rust
pub enum LineHeight {
    /// Line height in pixels.
    Pixels(u32),

    /// Line height in percent of the default line height.
    Percent(u32),
}

impl LineHeight {
    /// Converts the line height to an absolute pixel distance.
    pub fn to_absolute(self, base_line_height: u32) -> u32 { ... }
}

impl Default for LineHeight {
    // return LineHeight::Percent(100)
}

pub trait U32Ext {
    fn px(self) -> LineHeight;
    fn percent(self) -> LineHeight;
}

impl U32Ext for u32 { ... }
```

**Comment by bugadani** [comment]
LGTM!

**Comment by rfuest** [comment]
I'm not sure if this is more complicated than it needs to be. As I mentioned before I'm fine with using the `LineHeight` enum variants directly.

If we want to go down this route we would need to find a common place to put these units to make sure we don't include two different extension traits with the same method names. If we add some units in e-g and some in e-t we run into the risk to add the same units further down the road and get conflicts.

**Comment by bugadani** [comment]
> and get conflicts.

True, although I think conflicts may be avoided by some careful versioning.

> I'm not sure if this is more complicated than it needs to be.

It sure is. I can see the added complexity, and the potential problems. It would probably be best to not include extension methods in the first round, and maybe we can figure out a way to add them later, somehow. It's not a big deal, but a small quality of life feature. And also I find it cool enough, which probably is a thing to avoid in API design :)

**Comment by rfuest** [comment]
> And also I find it cool enough, which probably is a thing to avoid in API design :)

It is definitely cool, but if we adapt units IMO we should go all in and change all styles to use units. Otherwise we have an inconsistent API, where you sometimes need to add `.px()` and sometimes can use raw integer values. But this would be a considerable effort, because we would also need to implement a lot of math related traits to make expressions like `1.px() + 2.px()` possible.

**Comment by bugadani** [comment]
To be fair, that would be a step towards device-dependent point sizes ;) Imagine drawing a 2cm line in e-g! cc @jamwaffles

**Comment by rfuest** [comment]
Maybe in sometime in the future, but at the moment it would just make styles a little harder to use ;)

**Comment by jamwaffles** [comment]
> To be fair, that would be a step towards device-independent dimensions ;) Imagine drawing a 2cm line in e-g!

IMO that's outside e-g's remit and would be better served by an external crate. It's impossible to do e.g. `2.cm()` without knowing the pixel density of the target display, etc

**Comment by bugadani** [comment]
Fair enough, I (think) I intended that comment as a lame joke. But I think `2.cm()` would already work if one made a simple extension trait and used it consistently everywhere where right now a simple pixel is needed.
