### ISSUE TITLE
Rectangle in prelude

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-text#109]
Are you sure it's a good idea to include an external type in the prelude? I would agree that it's a good idea, if a program would only need to depend on e-t and not e-g. But all programs need to import types from e-g anyway, so that also including `Rectangle` isn't much more effort.

**Comment by bugadani** [comment]
To be honest, I have never been good at deciding if something belongs in a prelude or not. Right now I'm not even sure if e-t should have a prelude at all.

**Comment by rfuest** [comment]
> To be honest, I have never been good at deciding if something belongs in a prelude or not.

In e-g we only include traits in the prelude. If I remember correctly the only exceptions are `Point` and `Size`, which are used in nearly every crate that uses e-g.

> Right now I'm not even sure if e-t should have a prelude at all.

I think this might be the best solution.

**Comment by bugadani** [comment]
> In e-g we only include traits in the prelude.

That actually makes a lot of sense.
