### ISSUE TITLE
Support external font renderers

### ISSUE THREAD

**Issue by bugadani** [embedded-graphics/embedded-text#85]
A possible idea of doing this is to create an interface that should be implemented by various fonts and font renderers. In this case, embedded-text should provide implementations for everything supported by embedded-graphics and probably for the most popular third party renderers, within reason.

External renderers may or may not support more fancy text decoration, so the interface should abstract over these somehow.

**Comment by zack-emmert** [comment]
Would support for external font renderers include support for variable width fonts?

**Comment by bugadani** [comment]
There are a few assumptions currently in embedded-text, but the previous version was built with support for variable width fonts in embedded-graphics 0.6.

For future releases, this is not set in stone. However, the way I currently plan to support external renderers certainly makes support for variable width fonts possible.

**Comment by zack-emmert** [comment]
What sort of work would be needed to make this happen? I have some free time, so if I can get a sense of what needs doing I'd be happy to take a swing at it.

**Comment by bugadani** [comment]
Hmm, good question since I haven't really planned on the feature, just opened the ticket as something of a wishlist item. But:

1. a lot of internal refactor to transition away from pixel iterators
2. a bit of market research to see what third party font renderers exist
3. creating an abstraction over the possible font renderers that somehow integrate with the current feature set (static (TextBoxStyle) and dynamic (ANSI escape codes) styling, decorations (strikethrough, underlined)
4. maybe something else I don't know yet :)

Points 2 and 3 are probably the simpler ones if you'd like to chime in, considering how big a mess the current source is. And any help is appreciated :)
