### ISSUE TITLE
Refactor typestate configuration into enums

### ISSUE THREAD

**Issue by bugadani** [embedded-graphics/embedded-text#97]
VerticalOverdraw and HeightMode: #112

**Comment by rfuest** [comment]
Just to provide some feedback on the API from a user perspective: When I tried to change an example to be vertically centered I wasn't able to do this without looking at the docs. I could easily find the `vertical_alignment` method in `TextBoxStyleBuilder` by using code completion, but I had no idea that I could use the same `CenterAligned` type for both vertical and horizontal alignment.

**Comment by bugadani** [comment]
Were the options otherwise easy to discover?

**Comment by rfuest** [comment]
I only wanted to change this one and haven't paid much attention to the other options. But all options that use types instead of enums will have similar problems. If you decide to keep using type states I would suggest to list the available options in the docs for the corresponding builder methods.
